# Generated by Django 4.2.6 on 2023-10-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=9, verbose_name='Номера кабинета')),
            ],
            options={
                'verbose_name': 'кабинет',
                'verbose_name_plural': 'кабинеты',
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.office', verbose_name='Выберите кабинет')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'application',
            },
        ),
    ]
