# Generated by Django 4.2.6 on 2023-10-16 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_date',
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
