# Generated by Django 4.2.6 on 2023-10-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authuser_application_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='car',
            new_name='number_cab',
        ),
    ]
