# Generated by Django 4.2.6 on 2023-10-18 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_status_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и Время'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status_application',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Cтатус'),
        ),
    ]
