# Generated by Django 4.2.6 on 2023-10-21 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'labs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
