# Generated by Django 4.2.6 on 2023-10-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_application_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.authuser', verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'labs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лаборант'),
        ),
        migrations.CreateModel(
            name='Application_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
                ('status', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Статус')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
