# Generated by Django 4.2.6 on 2023-10-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application_History',
        ),
    ]
