# Generated by Django 4.2.6 on 2023-10-21 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_delete_application_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs_cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.office', verbose_name='Кабинет лаборанта')),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'labs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лаборант')),
            ],
            options={
                'verbose_name': 'Кабинеты лаборатов',
                'verbose_name_plural': 'Кабинеты лаборатов',
                'db_table': 'Labs_cabinets',
            },
        ),
    ]
